global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'multivm-nodes'
    static_configs:
      - targets: 
        - '172.20.0.11:9464'  # node1
        - '172.20.0.12:9464'  # node2
        - '172.20.0.13:9464'  # node3
        - '172.20.0.14:9464'  # node4
        - '172.20.0.15:9464'  # node5
        - '172.20.0.16:9464'  # node6
        - '172.20.0.17:9464'  # node7
